apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
